# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestDefaultSuite():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_testBE1Valid(self):
        self.driver.get("https://demo.guru99.com/V4/manager/Managerhomepage.php")
        self.driver.set_window_size(919, 696)
        time.sleep(1)

        # Hide footer and ads
        self.driver.execute_script("""
                       let footer = document.querySelector('p.barone');
                       if (footer) {
                           footer.style.display = 'none';
                       }

                       let ad = document.querySelector('img[alt="Try Xero for free"]');
                       if (ad && ad.parentElement) {
                           ad.parentElement.style.display = 'none';
                       }
                   """)



        # Stop the interval after click
        # self.driver.execute_script("clearInterval(window.adHiderInterval);")
        time.sleep(2)

        self.driver.find_element(By.LINK_TEXT, "Balance Enquiry").click()
        self.driver.find_element(By.NAME, "accountno").click()
        self.driver.find_element(By.NAME, "accountno").send_keys("1")
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(11) > td:nth-child(1)").click()
        error_message = self.driver.find_element(By.XPATH, '//*[@id="message2"]').text
        assert error_message == ""

    def test_testBE2negativeNum(self):
        self.driver.get("https://demo.guru99.com/V4/manager/Managerhomepage.php")
        self.driver.set_window_size(919, 696)
        time.sleep(1)

        # Hide footer and ads
        self.driver.execute_script("""
                       let footer = document.querySelector('p.barone');
                       if (footer) {
                           footer.style.display = 'none';
                       }

                       let ad = document.querySelector('img[alt="Try Xero for free"]');
                       if (ad && ad.parentElement) {
                           ad.parentElement.style.display = 'none';
                       }
                   """)

        # Stop the interval after click
        # self.driver.execute_script("clearInterval(window.adHiderInterval);")
        time.sleep(2)

        self.driver.find_element(By.LINK_TEXT, "Balance Enquiry").click()
        self.driver.find_element(By.NAME, "accountno").click()
        self.driver.find_element(By.NAME, "accountno").send_keys("-5")
        self.driver.find_element(By.CSS_SELECTOR, "tbody:nth-child(1) > tr:nth-child(1) > td").click()
        error_message = self.driver.find_element(By.XPATH, '//*[@id="message2"]').text
        assert error_message == "Negative numbers are not allowed"

    def test_testBE3alphabets(self):
        self.driver.get("https://demo.guru99.com/V4/manager/Managerhomepage.php")
        self.driver.set_window_size(919, 696)
        time.sleep(1)

        # Hide footer and ads
        self.driver.execute_script("""
                       let footer = document.querySelector('p.barone');
                       if (footer) {
                           footer.style.display = 'none';
                       }

                       let ad = document.querySelector('img[alt="Try Xero for free"]');
                       if (ad && ad.parentElement) {
                           ad.parentElement.style.display = 'none';
                       }
                   """)

        # Stop the interval after click
        # self.driver.execute_script("clearInterval(window.adHiderInterval);")
        time.sleep(2)

        self.driver.find_element(By.LINK_TEXT, "Balance Enquiry").click()
        self.driver.find_element(By.NAME, "accountno").click()
        self.driver.find_element(By.NAME, "accountno").send_keys("abc")
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(11) > td:nth-child(2)").click()
        error_message = self.driver.find_element(By.XPATH, '//*[@id="message2"]').text
        assert error_message == "Characters are not allowed"

    def test_testBE4blank(self):
        self.driver.get("https://demo.guru99.com/V4/manager/Managerhomepage.php")
        self.driver.set_window_size(919, 696)
        time.sleep(2)

        # Hide footer and ads
        self.driver.execute_script("""
                       let footer = document.querySelector('p.barone');
                       if (footer) {
                           footer.style.display = 'none';
                       }

                       let ad = document.querySelector('img[alt="Try Xero for free"]');
                       if (ad && ad.parentElement) {
                           ad.parentElement.style.display = 'none';
                       }
                   """)

        # Stop the interval after click
        # self.driver.execute_script("clearInterval(window.adHiderInterval);")
        time.sleep(2)

        self.driver.find_element(By.LINK_TEXT, "Balance Enquiry").click()
        self.driver.find_element(By.NAME, "accountno").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(11) > td:nth-child(2)")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).click_and_hold().perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > td:nth-child(2)")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).release().perform()
        error_message = self.driver.find_element(By.XPATH, '//*[@id="message2"]').text
        assert error_message == "Account Number must not be blank"

    def test_testBE5specialCharacter(self):
        self.driver.get("https://demo.guru99.com/V4/manager/Managerhomepage.php")
        self.driver.set_window_size(919, 696)
        time.sleep(1)

        # Hide footer and ads
        self.driver.execute_script("""
                       let footer = document.querySelector('p.barone');
                       if (footer) {
                           footer.style.display = 'none';
                       }

                       let ad = document.querySelector('img[alt="Try Xero for free"]');
                       if (ad && ad.parentElement) {
                           ad.parentElement.style.display = 'none';
                       }
                   """)



        # Stop the interval after click
        # self.driver.execute_script("clearInterval(window.adHiderInterval);")
        time.sleep(2)

        self.driver.find_element(By.LINK_TEXT, "Balance Enquiry").click()
        self.driver.find_element(By.NAME, "accountno").click()
        self.driver.find_element(By.NAME, "accountno").send_keys("@ $5")
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > td:nth-child(2)").click()
        error_message = self.driver.find_element(By.XPATH, '//*[@id="message2"]').text
        assert error_message == "Special characters are not allowed"

    def test_testBE6leadingZero(self):
        self.driver.get("https://demo.guru99.com/V4/manager/Managerhomepage.php")
        self.driver.set_window_size(919, 696)
        time.sleep(1)

        # Hide footer and ads
        self.driver.execute_script("""
                       let footer = document.querySelector('p.barone');
                       if (footer) {
                           footer.style.display = 'none';
                       }

                       let ad = document.querySelector('img[alt="Try Xero for free"]');
                       if (ad && ad.parentElement) {
                           ad.parentElement.style.display = 'none';
                       }
                   """)



        # Stop the interval after click
        # self.driver.execute_script("clearInterval(window.adHiderInterval);")
        time.sleep(2)

        self.driver.find_element(By.LINK_TEXT, "Balance Enquiry").click()
        self.driver.find_element(By.NAME, "accountno").click()
        self.driver.find_element(By.NAME, "accountno").send_keys("001")
        self.driver.find_element(By.CSS_SELECTOR, "tbody:nth-child(2) > tr > td").click()
        error_message = self.driver.find_element(By.XPATH, '//*[@id="message2"]').text
        assert error_message == "Invalid number"

    def test_testBE7longNumber(self):
        self.driver.get("https://demo.guru99.com/V4/manager/Managerhomepage.php")
        self.driver.set_window_size(919, 696)
        time.sleep(1)

        # Hide footer and ads
        self.driver.execute_script("""
                       let footer = document.querySelector('p.barone');
                       if (footer) {
                           footer.style.display = 'none';
                       }

                       let ad = document.querySelector('img[alt="Try Xero for free"]');
                       if (ad && ad.parentElement) {
                           ad.parentElement.style.display = 'none';
                       }
                   """)

        # Stop the interval after click
        # self.driver.execute_script("clearInterval(window.adHiderInterval);")
        time.sleep(2)

        self.driver.find_element(By.LINK_TEXT, "Balance Enquiry").click()
        self.driver.find_element(By.NAME, "accountno").click()
        self.driver.find_element(By.NAME, "accountno").send_keys("9999999999")
        self.driver.find_element(By.CSS_SELECTOR, "td > p:nth-child(2)").click()
        error_message = self.driver.find_element(By.XPATH, '//*[@id="message2"]').text
        assert error_message == ""
